name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [build-pre-rel, build-ramicro-pre-rel]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Build
        env:
          CERT_PWD: ${{ secrets.CERT_PWD }}
        run: .\doit.bat -ci

      - name: Upload Executable Artefact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: executable
          path: out/rel64/SumatraPDF-dll.exe
